# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# pnpm
export PNPM_HOME="${ZDOTDIR:-$HOME}/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end

# docker compose alias
alias dc="docker compose"

# pnpm suggestions
source "${ZDOTDIR:-$HOME}/.config/completion-for-pnpm.zsh"

# suggest autocompletion and history
ZSH_AUTOSUGGEST_STRATEGY=(history completion)